-- 전체 테이블 삭제 (재생성 전 초기화용)
-- CASCADE로 외래키 의존성 순서 신경 안 쓰고 한 번에 삭제
-- Supabase SQL Editor에서 실행 후, schema-init.sql을 이어서 실행할 것

DROP TABLE IF EXISTS mrkadjc01m CASCADE;
DROP TABLE IF EXISTS simrslt01d CASCADE;
DROP TABLE IF EXISTS simscnr01m CASCADE;
DROP TABLE IF EXISTS senradr01h CASCADE;
DROP TABLE IF EXISTS senradr01m CASCADE;
DROP TABLE IF EXISTS senlidr01h CASCADE;
DROP TABLE IF EXISTS senlidr01m CASCADE;
DROP TABLE IF EXISTS sensens01m CASCADE;
DROP TABLE IF EXISTS crddnst01h CASCADE;
DROP TABLE IF EXISTS crddnst01m CASCADE;
DROP TABLE IF EXISTS mrkrisk01m CASCADE;
DROP TABLE IF EXISTS mrkfcts01m CASCADE;
DROP TABLE IF EXISTS mrkaddr01d CASCADE;
DROP TABLE IF EXISTS mrkaddr01m CASCADE;
DROP TABLE IF EXISTS entchan01h CASCADE;
DROP TABLE IF EXISTS usrusrs01m CASCADE;
DROP TABLE IF EXISTS comcode01m CASCADE;

-- 혹시 이전 오타(usrusr501m)로 잘못 생성된 테이블이 남아있다면 같이 정리
DROP TABLE IF EXISTS usrusr501m CASCADE;
