-- 18개 테이블 전체 RLS 활성화 (소문자로 명시 - 대소문자 폴딩 불일치 방지)
ALTER TABLE comcode01m ENABLE ROW LEVEL SECURITY;
ALTER TABLE usrusrs01m ENABLE ROW LEVEL SECURITY;
ALTER TABLE entchan01h ENABLE ROW LEVEL SECURITY;
ALTER TABLE mrkaddr01m ENABLE ROW LEVEL SECURITY;
ALTER TABLE mrkaddr01d ENABLE ROW LEVEL SECURITY;
ALTER TABLE mrkfcts01m ENABLE ROW LEVEL SECURITY;
ALTER TABLE mrkrisk01m ENABLE ROW LEVEL SECURITY;
ALTER TABLE crddnst01m ENABLE ROW LEVEL SECURITY;
ALTER TABLE crddnst01h ENABLE ROW LEVEL SECURITY;
ALTER TABLE sensens01m ENABLE ROW LEVEL SECURITY;
ALTER TABLE senlidr01m ENABLE ROW LEVEL SECURITY;
ALTER TABLE senlidr01h ENABLE ROW LEVEL SECURITY;
ALTER TABLE senradr01m ENABLE ROW LEVEL SECURITY;
ALTER TABLE senradr01h ENABLE ROW LEVEL SECURITY;
ALTER TABLE simscnr01m ENABLE ROW LEVEL SECURITY;
ALTER TABLE simrslt01d ENABLE ROW LEVEL SECURITY;
ALTER TABLE mrkadjc01m ENABLE ROW LEVEL SECURITY;
